// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwJDH7FB_VbZj4Z-KwZESeqcLrbxoAb4Y',
    appId: '1:22073478183:web:196301514afe83b4fd9202',
    messagingSenderId: '22073478183',
    projectId: 'protrading-ai-2026',
    authDomain: 'protrading-ai-2026.firebaseapp.com',
    storageBucket: 'protrading-ai-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRjDdoTPCLNJq9m8_Zx4kB2A2MqUPIrqo',
    appId: '1:22073478183:android:28e25f8ee160fc7bfd9202',
    messagingSenderId: '22073478183',
    projectId: 'protrading-ai-2026',
    storageBucket: 'protrading-ai-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANCpdqslEtEXPFonPIk3QZAmpoJkQYAzk',
    appId: '1:22073478183:ios:1deac0d9017f2325fd9202',
    messagingSenderId: '22073478183',
    projectId: 'protrading-ai-2026',
    storageBucket: 'protrading-ai-2026.firebasestorage.app',
    iosBundleId: 'com.protrading.ai',
  );

}