import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'locale_cubit.dart';

class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'system_access': 'SYSTEM ACCESS',
      'create_account': 'CREATE ACCOUNT',
      'login_desc': 'Authorize your session to continue',
      'register_desc': 'Join the next generation of trading',
      'email_label': 'EMAIL ADDRESS',
      'password_label': 'ACCESS KEY / PASSWORD',
      'secure_login': 'SECURE LOGIN',
      'or': 'OR',
      'continue_with_google': 'CONTINUE WITH GOOGLE',
      'already_have_account': 'ALREADY HAVE AN ACCOUNT? LOGIN',
      'request_access_key': 'REQUEST ACCESS KEY',
      'fill_all_fields': 'Please fill all fields',
      'auth_invalid_credentials': 'Email or password is invalid.',
      'auth_email_in_use': 'This email is already registered.',
      'auth_weak_password': 'Choose a stronger password.',
      'auth_too_many_requests':
          'Too many attempts. Wait a moment and try again.',
      'auth_popup_cancelled': 'Google sign-in was cancelled or blocked.',
      'auth_generic_error': 'Authentication is temporarily unavailable.',
      'neural_network_signals': 'Evidence-Based Market Analysis',
      'zero_latency': 'Risk-Gated Paper Execution',
      'global_liquidity': 'Multi-Timeframe Market Context',
      'execution_engine': 'EXECUTION ENGINE',
      'lot_size': 'LOT SIZE',
      'sell': 'SELL',
      'buy': 'BUY',
      'analyze_data': 'ANALYZE DATA (AI)',
      'ai_analyzing': 'AI ANALYZING...',
      'active_signals': 'ACTIVE SIGNALS',
      'no_signals': 'No signals yet. Press Analyze AI.',
      'equity': 'Equity',
      'link_api': 'LINK BROKER API',
      'link_broker_title': 'Link MT4/MT5 Account',
      'link_broker_desc':
          'The system only requires Read-only password to sync. Absolutely safe, the system CANNOT trade or withdraw your money.',
      'account_number': 'Account Number (Login)',
      'investor_password': 'Password (Investor Password)',
      'broker_server': 'Broker Server (e.g. Exness-Real)',
      'cancel': 'Cancel',
      'link_now': 'Link Now',
      'sending_link_request': 'Sending link request to Server...',
      'analyzing_request': 'Sending AI analysis request...',
      'trading_room': 'Trading Room',
      'journal': 'Journal',
      'news_feed': 'News Feed',
      'backtest_dojo': 'Backtest Dojo',
      'community': 'Community',
      'market_radar': 'Market Radar',
      'referral_hub': 'Referral Hub',
      'referral_page_title': 'Loyalty & Referrals',
      'referral_page_desc':
          'Referral network and reward history when available.',
      'profile': 'Profile',
      'admin_center': 'Admin Center',
      'xauusd_label': 'XAUUSD (Gold)',
      'eurusd_label': 'EURUSD (Forex)',
      'btcusd_label': 'BTCUSD (Crypto)',
      'loading': 'Loading...',
      'common_data_unavailable':
          'Data is temporarily unavailable. Please try again.',
      'common_access_denied': 'You do not have access to this page.',
      'backtest_auth_required': 'Sign in to start a backtest session.',
      'backtest_first_candle': 'Go to first candle',
      'backtest_previous_candle': 'Previous candle',
      'backtest_play': 'Play replay',
      'backtest_pause': 'Pause replay',
      'backtest_next_candle': 'Next candle',
      'news_ai_unavailable':
          'AI analysis is temporarily unavailable. Please try again.',
      'community_post_success': 'Analysis posted successfully.',
      'community_post_failed': 'Unable to publish this post.',
      'community_post_hint': 'Share your market analysis...',
      'community_post_button': 'Post analysis',
      'community_feed_empty': 'No community posts yet.',
      'community_likes': 'Likes',
      'community_like_action': 'Like',
      'community_liked': 'Liked',
      'community_like_failed': 'Unable to like this post. Please retry.',
      'community_comments': 'Comments',
      'community_profit_hidden': 'Verified result hidden',
      'community_leaderboard_title': 'Leaderboard',
      'community_top_rankings': 'Top rankings',
      'community_volume': 'Volume',
      'radar_data_unavailable': 'Radar data is unavailable.',
      'admin_action_failed': 'The admin action could not be completed.',
      'admin_broadcast_sent': 'Broadcast sent.',
      'admin_request_approved': 'Request approved.',
      'admin_request_rejected': 'Request rejected.',
      'admin_ai_config_saved': 'AI configuration saved.',
      'admin_kill_switch_saved': 'Trading control updated.',
      'admin_risk_saved': 'Global risk configuration saved.',
      'admin_radar_saved': 'Radar configuration saved.',
      'tr_risk_saved': 'Risk configuration saved.',
      'tr_risk_save_failed': 'Unable to save risk configuration.',
      'tr_analysis_requested': 'AI analysis request accepted.',
      'tr_analysis_request_failed': 'Unable to request AI analysis.',
      'tr_trade_executed': 'Paper trade executed.',
      'tr_trade_partial':
          'Some take-profit legs executed. Review open positions before retrying.',
      'tr_trade_failed': 'Unable to execute the paper trade.',
      'tr_trade_closed': 'Paper trade closed.',
      'tr_trade_close_failed': 'Unable to close the paper trade.',
      'terminal_positions_stale':
          'Position data may be stale while the server reconnects.',
      'news_sentiment_unavailable': 'Sentiment data is unavailable.',
      'news_source_unavailable': 'Source unavailable',
      'news_time_unavailable': 'Time unavailable',
      'community_time_unavailable': 'Time unavailable',
      'community_leaderboard_empty': 'No verified rankings available.',
      'referral_link_copied': 'Referral link copied.',
      'order_executed': '{type} Order Executed: {lot} Lots',
      'performance_analytics': 'Performance Analytics',
      'journal_desc': 'Real-time trading performance & behavioral insights.',
      'total_net_profit': 'TOTAL NET PROFIT',
      'win_rate': 'WIN RATE',
      'profit_factor': 'PROFIT FACTOR',
      'avg_rr_ratio': 'AVG R:R RATIO',
      'above_target': 'ABOVE TARGET',
      'equity_growth_curve': 'EQUITY GROWTH CURVE',
      'start': 'START',
      'current': 'CURRENT',
      'ai_performance_insight': 'AI PERFORMANCE INSIGHT',
      'ai_insight_desc':
          '"You are currently showing 12% higher profit variance during the NY open. Suggest waiting for 5-min candle confirmation."',
      'psychology_score': 'PSYCHOLOGY SCORE',
      'discipline': 'DISCIPLINE',
      'risk_adherence': 'RISK ADHERENCE',
      'error_loss_heatmap': 'ERROR & LOSS DENSITY HEATMAP',
      'mon': 'MON',
      'fri': 'FRI',
      'global_trade_log': 'GLOBAL TRADE LOG',
      'export_csv': 'EXPORT CSV',
      'filter': 'FILTER',
      'symbol': 'SYMBOL',
      'action': 'ACTION',
      'size': 'SIZE',
      'entry': 'ENTRY',
      'exit': 'EXIT',
      'net_pl': 'NET P/L',
      'swap': 'SWAP',
      'commission': 'COMMISSION',
      'slippage': 'SLIPPAGE',
      'listen_ai_advice': 'Listen to AI Advice',
      'journal_audio_unavailable': 'Audio advice is unavailable',
      'journal_play_voice': 'Play voice analysis',
      'journal_stop_voice': 'Stop voice analysis',
      'cutoff_locked_notice':
          'Daily loss limit reached. Analysis and new paper trades are locked.',
      'cutoff_review_action': 'Review',
      'cutoff_review_title': 'Daily loss review',
      'cutoff_review_body':
          'Review the recorded loss before acknowledging. The lock lasts at least until the next UTC day.',
      'cutoff_session': 'UTC session',
      'cutoff_realized': 'Realized P&L',
      'cutoff_floating': 'Floating P&L',
      'cutoff_limit': 'Loss limit',
      'cutoff_acknowledge': 'I acknowledge',
      'cutoff_acknowledged_notice':
          'Acknowledged. Reload after the next UTC day to check whether trading is available.',
      'cutoff_review_unavailable': 'Loss review is temporarily unavailable.',
      'cutoff_status_unavailable':
          'Risk status is unavailable. Analysis and new paper trades stay locked.',
      // Risk Config Modal
      'risk_config_title': 'RISK CONFIGURATION',
      'risk_config_subtitle':
          'Set your risk parameters before initializing the chart',
      'risk_config_balance': 'ACCOUNT BALANCE',
      'risk_config_balance_hint': 'e.g. 10000',
      'risk_config_balance_error': 'Balance must be greater than 0',
      'risk_config_risk': 'RISK PER TRADE',
      'risk_config_risk_hint': '1.0',
      'risk_config_risk_error': 'Enter a value between 0.1% and 10%',
      'risk_config_max_loss': 'MAX DAILY LOSS',
      'risk_config_max_loss_hint': '5.0',
      'risk_config_max_loss_error': 'Enter a value between 1% and 50%',
      'risk_config_btn': 'INITIALIZE CHART',
      // Trading Room - Navbar
      'tr_connecting': 'CONNECTING...',
      'tr_live': 'LIVE',
      'tr_link_api': 'Link API',
      'tr_logout_tooltip': 'Logout',
      // Trading Room - Sub Tab
      'tr_tab_label': 'Trading Room',
      // Trading Room - Link Broker Dialog
      'tr_link_broker_title': 'Link Broker Account',
      'tr_link_broker_desc':
          'Connect MT4/MT5 to sync account metrics. Execution remains paper trading.',
      'tr_account_number': 'Account Number',
      'tr_investor_password': 'Investor Password',
      'tr_broker_server': 'Broker Server',
      'tr_cancel': 'Cancel',
      'tr_link_now': 'Link Now',
      'tr_link_sending': 'Sending link request...',
      // Terminal Panel - Tabs
      'terminal_tab_trade': 'TRADE',
      'terminal_tab_exposure': 'EXPOSURE',
      'terminal_tab_history': 'HISTORY',
      // Terminal Panel - Table headers
      'terminal_col_order': 'ORDER',
      'terminal_col_time': 'TIME',
      'terminal_col_type': 'TYPE',
      'terminal_col_size': 'SIZE',
      'terminal_col_symbol': 'SYMBOL',
      'terminal_col_price': 'PRICE',
      'terminal_col_sl': 'S/L',
      'terminal_col_tp': 'T/P',
      'terminal_col_profit': 'PROFIT',
      'terminal_col_action': 'ACTION',
      'terminal_col_open': 'OPEN',
      'terminal_col_close': 'CLOSE',
      // Terminal Panel - States
      'terminal_no_positions': 'No open positions',
      'terminal_no_exposure': 'No exposure data',
      'terminal_no_history': 'No trade history',
      'terminal_close_btn': 'CLOSE',
      'terminal_long': 'LONG',
      'terminal_short': 'SHORT',
      'terminal_net': 'NET',
      'terminal_open_label': 'OPEN',
      // Terminal Panel - Footer
      'terminal_balance': 'Balance',
      'terminal_equity': 'Equity',
      'terminal_total_pnl': 'Total P&L',
      // Execution Panel
      'exec_engine': 'EXECUTION ENGINE',
      'exec_suggested_lot': 'Suggested Lot',
      'exec_risk': 'Risk',
      'exec_entry': 'Entry',
      'exec_stop_loss': 'STOP LOSS',
      'exec_take_profit': 'TAKE PROFIT',
      'exec_tp_allocation': 'Volume allocation',
      'exec_tp_total': 'Total',
      'exec_tp_allocation_invalid': 'TP allocation must total exactly 100%.',
      'exec_tp_volume_too_small':
          'Suggested lot is too small for this three-part split.',
      'exec_trading_mode': 'TRADING MODE',
      'exec_active_signal': 'ACTIVE SIGNAL',
      'exec_probability': 'Probability',
      'exec_locked': 'TRADING LOCKED',
      'exec_max_loss': 'Max daily loss reached',
      'exec_manual': 'MANUAL ENTRY',
      'exec_execute_long': 'EXECUTE LONG',
      'exec_execute_short': 'EXECUTE SHORT',
      'exec_sl': 'Stop Loss',
      'exec_sl_single': 'Single SL',
      'forecast_title': 'AI FORECAST',
      // legacy keys kept for safety but no longer SL1/2/3 copy
      'exec_sl_tight': 'Stop Loss',
      'exec_sl_normal': 'Stop Loss',
      'exec_sl_wide': 'Stop Loss',
      // AI Chat Panel
      'ai_title': 'AI ASSISTANT',
      'ai_active': 'Responses depend on available sources',
      'ai_placeholder': 'Ask AI about the chart...',
      'ai_empty_hint': 'Ask AI about the chart,\nmarket conditions, or signals',
      // Journal Screen
      'journal_page_title': 'Performance Analytics',
      'journal_page_desc':
          'Track your trading performance, analyze patterns, and improve your edge.',
      'journal_above_target': 'Above target',
      'journal_below_target': 'Below target',
      'journal_no_trades': 'No trades yet',
      'journal_no_trades_recorded': 'No trades recorded yet',
      'journal_no_trades_ai':
          'No trades recorded yet. Start trading to see AI performance insights.',
      'journal_playing_voice': 'Playing Voice Analysis...',
      'journal_export_csv': 'Export CSV',
      'journal_filter': 'Filter',
      'journal_heatmap_title': 'PROFIT/LOSS HEATMAP',
      'journal_no_trades_cell': 'No trades',
      'journal_heatmap_loss': 'Loss',
      'journal_heatmap_profit': 'Profit',
      'journal_trade_log': 'GLOBAL TRADE LOG',
      'journal_lots': 'Lots',
      // News Feed Screen
      'news_page_title': 'Market Intelligence',
      'news_page_desc': 'Market news and sentiment from available sources.',
      'news_sentiment_title': 'GLOBAL SENTIMENT PULSE',
      'news_bullish': 'MARKET MOOD: BULLISH',
      'news_bearish': 'MARKET MOOD: BEARISH',
      'news_neutral_bullish': 'MARKET MOOD: NEUTRAL-BULLISH',
      'news_neutral_bearish': 'MARKET MOOD: NEUTRAL-BEARISH',
      'news_fear': 'FEAR',
      'news_neutral': 'NEUTRAL',
      'news_greed': 'GREED',
      'news_no_articles': 'No news articles available',
      'news_ai_placeholder': 'Ask about market sentiment...',
      'news_ai_title': 'AI MARKET ANALYST',
      'news_ai_clear_tooltip': 'Clear chat history',
      'news_ai_clear_title': 'Clear history?',
      'news_ai_clear_content': 'All chat history will be permanently deleted.',
      'news_ai_cancel': 'Cancel',
      'news_ai_delete': 'Delete',
      'news_ai_empty_hint': 'Ask AI about news\nand market analysis',
      'news_ai_welcome':
          'Ask about market sentiment, news impact, or trading analysis. Answers are available when the AI service is configured.',
      // ─── Profile Screen ───
      'profile_title': 'Security & Profile',
      'profile_subtitle':
          'Manage your identity, broker accounts and API quotas.',
      'profile_system_online': '● PROTRADING AI SYSTEM ONLINE',
      'profile_connecting': '○ CONNECTING...',
      // Profile Info
      'profile_edit_username': 'Edit Username',
      'profile_new_username': 'New username',
      'profile_username_updated': 'Username updated!',
      'profile_username_update_failed': 'Username could not be updated.',
      'profile_save': 'SAVE',
      // Change Password
      'profile_change_key': 'Change Access Key',
      'profile_current_password': 'Current Password',
      'profile_new_password': 'New Password',
      'profile_confirm_password': 'Confirm New Password',
      'profile_password_mismatch': 'Passwords do not match!',
      'profile_password_short': 'Password must be at least 6 characters!',
      'profile_password_change_failed':
          'Password could not be changed. Verify the current password and try again.',
      'profile_password_changed': 'Password changed successfully!',
      'profile_change_btn': 'CHANGE',
      // Broker Accounts
      'profile_broker_accounts': 'BROKER ACCOUNTS',
      'profile_link_new': 'LINK NEW',
      'profile_no_accounts': 'No accounts linked yet.',
      'profile_link_broker_title': 'Link Broker Account',
      'profile_platform': 'Platform',
      'profile_broker_server': 'Broker Server (e.g. Exness-Real10)',
      'profile_login_id': 'Login ID',
      'profile_trading_password': 'Trading Password',
      'profile_security_notice':
          'App only requires Read-only password to sync. Absolutely safe, the system CANNOT trade or withdraw your money.',
      'profile_link_account': 'LINK ACCOUNT',
      'profile_link_sent':
          'Linking request sent. Check status in a few moments.',
      'profile_link_failed': 'Broker account could not be linked.',
      // Quota
      'profile_api_requests': 'API REQUESTS',
      'profile_backtest_sessions': 'BACKTEST SESSIONS',
      'profile_neural_storage': 'NEURAL STORAGE',
      // Security
      'profile_security_settings': 'SECURITY SETTINGS',
      'profile_2fa_title': 'Two-Factor Authentication',
      'profile_2fa_subtitle': 'Protect your account with 2FA.',
      'profile_2fa_unavailable':
          '2FA setup is unavailable until Firebase MFA is configured.',
      'profile_2fa_enabled': '2FA Enabled',
      'profile_2fa_disabled': '2FA Disabled',
      // Preferences
      'profile_preferences': 'PREFERENCES',
      'profile_push_notifications': 'Push Notifications',
      'profile_push_notifications_subtitle': 'Receive trade signals and alerts',
      'profile_language': 'Language',
      'profile_language_vi': 'Tiếng Việt',
      'profile_language_en': 'English',
      'profile_data_sharing': 'Share Debug Data',
      'profile_data_sharing_subtitle':
          'Allow sharing diagnostic data (Default: OFF)',
      // Stats
      'profile_trades': 'TRADES',
      'profile_win_rate': 'WIN RATE',
      'profile_rank': 'RANK',
      // Day 5
      'profile_link_on_web_only':
          'Link MT4/MT5 only on Web (Profile → Link Broker). Mobile uses API Relay — no broker credentials on device.',
      'sync_gate_title': 'CONNECT YOUR BROKER',
      'sync_gate_body':
          'Link MT4/MT5 on Web to unlock live relay, Journal clarity, and synced risk. Or continue in manual mode with Input Constraint.',
      'sync_gate_connect': 'CONNECT NOW',
      'sync_gate_skip': 'SKIP & ENTER MANUALLY',
      'journal_locked_title': 'JOURNAL LOCKED',
      'journal_locked_body':
          'Link your broker on Web (Profile → Link Broker) to unlock full Journal analytics.',
      'ai_fallback_label': 'FALLBACK MODE',
    },
    'vi': {
      'system_access': 'ĐĂNG NHẬP HỆ THỐNG',
      'create_account': 'TẠO TÀI KHOẢN',
      'login_desc': 'Xác thực phiên của bạn để tiếp tục',
      'register_desc': 'Tham gia thế hệ giao dịch mới',
      'email_label': 'ĐỊA CHỈ EMAIL',
      'password_label': 'MẬT KHẨU / KHÓA TRUY CẬP',
      'secure_login': 'ĐĂNG NHẬP BẢO MẬT',
      'or': 'HOẶC',
      'continue_with_google': 'TIẾP TỤC VỚI GOOGLE',
      'already_have_account': 'ĐÃ CÓ TÀI KHOẢN? ĐĂNG NHẬP',
      'request_access_key': 'YÊU CẦU KHÓA TRUY CẬP',
      'fill_all_fields': 'Vui lòng điền đủ thông tin',
      'auth_invalid_credentials': 'Email hoặc mật khẩu không hợp lệ.',
      'auth_email_in_use': 'Email này đã được đăng ký.',
      'auth_weak_password': 'Hãy chọn mật khẩu mạnh hơn.',
      'auth_too_many_requests':
          'Có quá nhiều lần thử. Vui lòng chờ và thử lại.',
      'auth_popup_cancelled': 'Đăng nhập Google đã bị hủy hoặc chặn.',
      'auth_generic_error': 'Dịch vụ xác thực tạm thời không khả dụng.',
      'neural_network_signals': 'Phân Tích Thị Trường Có Bằng Chứng',
      'zero_latency': 'Giao Dịch Giấy Có Kiểm Soát Rủi Ro',
      'global_liquidity': 'Bối Cảnh Thị Trường Đa Khung Thời Gian',
      'execution_engine': 'ĐỘNG CƠ KHỚP LỆNH',
      'lot_size': 'KHỐI LƯỢNG (LOT)',
      'sell': 'BÁN',
      'buy': 'MUA',
      'analyze_data': 'PHÂN TÍCH DỮ LIỆU (AI)',
      'ai_analyzing': 'AI ĐANG PHÂN TÍCH...',
      'active_signals': 'TÍN HIỆU ĐANG HOẠT ĐỘNG',
      'no_signals': 'Chưa có tín hiệu. Nhấn Phân tích AI.',
      'equity': 'Vốn',
      'link_api': 'LIÊN KẾT API SÀN',
      'link_broker_title': 'Liên kết tài khoản MT4/MT5',
      'link_broker_desc':
          'Hệ thống chỉ yêu cầu Mật khẩu chỉ đọc (Read-only password) để đồng bộ. Tuyệt đối an toàn, hệ thống KHÔNG THỂ vào lệnh hoặc rút tiền của bạn.',
      'account_number': 'Số tài khoản (Login)',
      'investor_password': 'Mật khẩu (Investor Password)',
      'broker_server': 'Server Sàn (VD: Exness-Real)',
      'cancel': 'Hủy',
      'link_now': 'Liên Kết Ngay',
      'sending_link_request': 'Đang gửi yêu cầu liên kết đến Server...',
      'analyzing_request': 'Đã gửi yêu cầu phân tích dữ liệu AI...',
      'trading_room': 'Phòng Giao Dịch',
      'journal': 'Nhật Ký',
      'news_feed': 'Tin Tức Thị Trường',
      'backtest_dojo': 'Sân Luyện Tập',
      'community': 'Cộng Đồng',
      'market_radar': 'Radar Phân Tích',
      'referral_hub': 'Giới Thiệu & Đối Tác',
      'referral_page_title': 'Giới Thiệu & Đối Tác',
      'referral_page_desc':
          'Mạng lưới giới thiệu và lịch sử thưởng khi có dữ liệu.',
      'profile': 'Hồ Sơ Của Tôi',
      'admin_center': 'Quản Trị Hệ Thống',
      'xauusd_label': 'XAUUSD (Vàng)',
      'eurusd_label': 'EURUSD (Forex)',
      'btcusd_label': 'BTCUSD (Crypto)',
      'loading': 'Đang tải...',
      'common_data_unavailable':
          'Dữ liệu tạm thời chưa khả dụng. Vui lòng thử lại.',
      'common_access_denied': 'Bạn không có quyền truy cập trang này.',
      'backtest_auth_required': 'Hãy đăng nhập để bắt đầu phiên backtest.',
      'backtest_first_candle': 'Về nến đầu tiên',
      'backtest_previous_candle': 'Nến trước',
      'backtest_play': 'Phát mô phỏng',
      'backtest_pause': 'Tạm dừng mô phỏng',
      'backtest_next_candle': 'Nến tiếp theo',
      'news_ai_unavailable':
          'Phân tích AI tạm thời chưa khả dụng. Vui lòng thử lại.',
      'community_post_success': 'Đã đăng bài phân tích.',
      'community_post_failed': 'Không thể đăng bài này.',
      'community_post_hint': 'Chia sẻ phân tích thị trường của bạn...',
      'community_post_button': 'Đăng phân tích',
      'community_feed_empty': 'Chưa có bài viết cộng đồng.',
      'community_likes': 'Lượt thích',
      'community_like_action': 'Thích',
      'community_liked': 'Đã thích',
      'community_like_failed': 'Không thể thích bài viết. Vui lòng thử lại.',
      'community_comments': 'Bình luận',
      'community_profit_hidden': 'Đã ẩn kết quả xác minh',
      'community_leaderboard_title': 'Bảng xếp hạng',
      'community_top_rankings': 'Xếp hạng cao nhất',
      'community_volume': 'Khối lượng',
      'radar_data_unavailable': 'Dữ liệu Radar chưa khả dụng.',
      'admin_action_failed': 'Không thể hoàn tất thao tác quản trị.',
      'admin_broadcast_sent': 'Đã gửi thông báo.',
      'admin_request_approved': 'Đã duyệt yêu cầu.',
      'admin_request_rejected': 'Đã từ chối yêu cầu.',
      'admin_ai_config_saved': 'Đã lưu cấu hình AI.',
      'admin_kill_switch_saved': 'Đã cập nhật điều khiển giao dịch.',
      'admin_risk_saved': 'Đã lưu cấu hình rủi ro toàn cục.',
      'admin_radar_saved': 'Đã lưu cấu hình Radar.',
      'tr_risk_saved': 'Đã lưu cấu hình rủi ro.',
      'tr_risk_save_failed': 'Không thể lưu cấu hình rủi ro.',
      'tr_analysis_requested': 'Hệ thống đã nhận yêu cầu phân tích AI.',
      'tr_analysis_request_failed': 'Không thể gửi yêu cầu phân tích AI.',
      'tr_trade_executed': 'Đã khớp lệnh giao dịch giấy.',
      'tr_trade_partial':
          'Một số phần chốt lời đã khớp. Hãy kiểm tra vị thế trước khi thử lại.',
      'tr_trade_failed': 'Không thể khớp lệnh giao dịch giấy.',
      'tr_trade_closed': 'Đã đóng lệnh giao dịch giấy.',
      'tr_trade_close_failed': 'Không thể đóng lệnh giao dịch giấy.',
      'terminal_positions_stale':
          'Dữ liệu vị thế có thể đã cũ trong lúc kết nối lại máy chủ.',
      'news_sentiment_unavailable': 'Dữ liệu cảm xúc chưa khả dụng.',
      'news_source_unavailable': 'Chưa có nguồn',
      'news_time_unavailable': 'Chưa có thời gian',
      'community_time_unavailable': 'Chưa có thời gian',
      'community_leaderboard_empty': 'Chưa có bảng xếp hạng đã xác minh.',
      'referral_link_copied': 'Đã sao chép liên kết giới thiệu.',
      'order_executed': 'Khớp lệnh {type}: {lot} Lot',
      'performance_analytics': 'Phân Tích Hiệu Suất',
      'journal_desc': 'Hiệu suất giao dịch thời gian thực & phân tích hành vi.',
      'total_net_profit': 'TỔNG LỢI NHUẬN RÒNG',
      'win_rate': 'TỶ LỆ THẮNG',
      'profit_factor': 'HỆ SỐ LỢI NHUẬN',
      'avg_rr_ratio': 'TỶ LỆ R:R TRUNG BÌNH',
      'above_target': 'VƯỢT MỤC TIÊU',
      'equity_growth_curve': 'BIỂU ĐỒ TĂNG TRƯỞNG VỐN',
      'start': 'BẮT ĐẦU',
      'current': 'HIỆN TẠI',
      'ai_performance_insight': 'AI PHÂN TÍCH HIỆU SUẤT',
      'ai_insight_desc':
          '"Bạn đang có phương sai lợi nhuận cao hơn 12% vào lúc mở cửa phiên Mỹ. Đề xuất chờ xác nhận nến 5 phút."',
      'psychology_score': 'ĐIỂM TÂM LÝ',
      'discipline': 'KỶ LUẬT',
      'risk_adherence': 'TUÂN THỦ RỦI RO',
      'error_loss_heatmap': 'BẢN ĐỒ NHIỆT MẬT ĐỘ LỖ & SAI SÓT',
      'mon': 'T2',
      'fri': 'T6',
      'global_trade_log': 'NHẬT KÝ GIAO DỊCH TỔNG',
      'export_csv': 'XUẤT CSV',
      'filter': 'LỌC',
      'symbol': 'MÃ',
      'action': 'LỆNH',
      'size': 'KL',
      'entry': 'GIÁ VÀO',
      'exit': 'GIÁ ĐÓNG',
      'net_pl': 'LỢI NHUẬN RÒNG',
      'swap': 'PHÍ QUA ĐÊM',
      'commission': 'HOA HỒNG',
      'slippage': 'TRƯỢT GIÁ',
      'listen_ai_advice': 'Nghe AI Cố Vấn',
      'journal_audio_unavailable': 'Chưa có bản âm thanh tư vấn',
      'journal_play_voice': 'Phát phân tích giọng nói',
      'journal_stop_voice': 'Dừng phân tích giọng nói',
      'cutoff_locked_notice':
          'Đã chạm giới hạn lỗ ngày. Phân tích và lệnh giấy mới đang bị khóa.',
      'cutoff_review_action': 'Xem lại',
      'cutoff_review_title': 'Xem lại mức lỗ ngày',
      'cutoff_review_body':
          'Xem số liệu lỗ đã ghi trước khi xác nhận. Khóa duy trì ít nhất đến ngày UTC tiếp theo.',
      'cutoff_session': 'Phiên UTC',
      'cutoff_realized': 'Lãi/lỗ đã chốt',
      'cutoff_floating': 'Lãi/lỗ đang mở',
      'cutoff_limit': 'Giới hạn lỗ',
      'cutoff_acknowledge': 'Tôi xác nhận',
      'cutoff_acknowledged_notice':
          'Đã xác nhận. Tải lại trang sau khi sang ngày UTC tiếp theo để kiểm tra quyền giao dịch.',
      'cutoff_review_unavailable': 'Chưa thể xem lại mức lỗ lúc này.',
      'cutoff_status_unavailable':
          'Chưa tải được trạng thái rủi ro. Phân tích và lệnh giấy mới tiếp tục bị khóa.',
      // Risk Config Modal
      'risk_config_title': 'CẤU HÌNH RỦI RO',
      'risk_config_subtitle': 'Thiết lập thông số trước khi khởi động biểu đồ',
      'risk_config_balance': 'SỐ DƯ TÀI KHOẢN',
      'risk_config_balance_hint': 'VD: 10000',
      'risk_config_balance_error': 'Vui lòng nhập số dư lớn hơn 0',
      'risk_config_risk': 'RỦI RO MỖI LỆNH',
      'risk_config_risk_hint': '1.0',
      'risk_config_risk_error': 'Nhập từ 0.1% đến 10%',
      'risk_config_max_loss': 'GIỚI HẠN LỖ MỖI NGÀY',
      'risk_config_max_loss_hint': '5.0',
      'risk_config_max_loss_error': 'Nhập từ 1% đến 50%',
      'risk_config_btn': 'KHỞI ĐỘNG BIỂU ĐỒ',
      // Trading Room - Navbar
      'tr_connecting': 'ĐANG KẾT NỐI...',
      'tr_live': 'TRỰC TIẾP',
      'tr_link_api': 'Liên kết API',
      'tr_logout_tooltip': 'Đăng xuất',
      // Trading Room - Sub Tab
      'tr_tab_label': 'Phòng Giao Dịch',
      // Trading Room - Link Broker Dialog
      'tr_link_broker_title': 'Liên Kết Tài Khoản Sàn',
      'tr_link_broker_desc':
          'Kết nối MT4/MT5 để đồng bộ số liệu tài khoản. Hệ thống vẫn chỉ giao dịch giấy.',
      'tr_account_number': 'Số Tài Khoản',
      'tr_investor_password': 'Mật Khẩu Investor',
      'tr_broker_server': 'Server Sàn',
      'tr_cancel': 'Hủy',
      'tr_link_now': 'Liên Kết Ngay',
      'tr_link_sending': 'Đang gửi yêu cầu liên kết...',
      // Terminal Panel - Tabs
      'terminal_tab_trade': 'LỆNH',
      'terminal_tab_exposure': 'RỦI RO',
      'terminal_tab_history': 'LỊCH SỬ',
      // Terminal Panel - Table headers
      'terminal_col_order': 'LỆNH',
      'terminal_col_time': 'GIỜ',
      'terminal_col_type': 'LOẠI',
      'terminal_col_size': 'KL',
      'terminal_col_symbol': 'MÃ',
      'terminal_col_price': 'GIÁ',
      'terminal_col_sl': 'Cắt Lỗ',
      'terminal_col_tp': 'Chốt Lời',
      'terminal_col_profit': 'LỢI NHUẬN',
      'terminal_col_action': 'THAO TÁC',
      'terminal_col_open': 'MỞ',
      'terminal_col_close': 'ĐÓNG',
      // Terminal Panel - States
      'terminal_no_positions': 'Chưa có lệnh mở',
      'terminal_no_exposure': 'Chưa có dữ liệu rủi ro',
      'terminal_no_history': 'Chưa có lịch sử giao dịch',
      'terminal_close_btn': 'ĐÓNG',
      'terminal_long': 'LONG',
      'terminal_short': 'SHORT',
      'terminal_net': 'RÒNG',
      'terminal_open_label': 'MỞ',
      // Terminal Panel - Footer
      'terminal_balance': 'Số Dư',
      'terminal_equity': 'Vốn',
      'terminal_total_pnl': 'Tổng L/N',
      // Execution Panel
      'exec_engine': 'BẢNG ĐIỀU KHIỂN',
      'exec_suggested_lot': 'Lot Gợi Ý',
      'exec_risk': 'Rủi Ro',
      'exec_entry': 'Giá Vào',
      'exec_stop_loss': 'CẮT LỖ',
      'exec_take_profit': 'CHỐT LỜI',
      'exec_tp_allocation': 'Phân bổ khối lượng',
      'exec_tp_total': 'Tổng',
      'exec_tp_allocation_invalid': 'Tỷ lệ TP phải có tổng chính xác 100%.',
      'exec_tp_volume_too_small': 'Lot gợi ý quá nhỏ để chia thành ba phần.',
      'exec_trading_mode': 'CHẾ ĐỘ GIAO DỊCH',
      'exec_active_signal': 'TÍN HIỆU HIỆN TẠI',
      'exec_probability': 'Xác Suất',
      'exec_locked': 'KHÓA GIAO DỊCH',
      'exec_max_loss': 'Đã đạt giới hạn lỗ ngày',
      'exec_manual': 'VÀO LỆNH THỦ CÔNG',
      'exec_execute_long': 'MUA (LONG)',
      'exec_execute_short': 'BÁN (SHORT)',
      'exec_sl': 'Cắt Lỗ',
      'exec_sl_single': 'Một mức SL',
      'forecast_title': 'DỰ BÁO AI',
      'exec_sl_tight': 'Cắt Lỗ',
      'exec_sl_normal': 'Cắt Lỗ',
      'exec_sl_wide': 'Cắt Lỗ',
      // AI Chat Panel
      'ai_title': 'TRỢ LÝ AI',
      'ai_active': 'Câu trả lời phụ thuộc vào nguồn dữ liệu khả dụng',
      'ai_placeholder': 'Hỏi AI về biểu đồ...',
      'ai_empty_hint':
          'Hỏi AI về biểu đồ,\nđiều kiện thị trường, hoặc tín hiệu',
      // Journal Screen
      'journal_page_title': 'Phân Tích Hiệu Suất',
      'journal_page_desc':
          'Theo dõi hiệu suất giao dịch, phân tích xu hướng và cải thiện lợi thế của bạn.',
      'journal_above_target': 'Trên mục tiêu',
      'journal_below_target': 'Dưới mục tiêu',
      'journal_no_trades': 'Chưa có lệnh nào',
      'journal_no_trades_recorded': 'Chưa có lệnh nào được ghi lại',
      'journal_no_trades_ai':
          'Chưa có lệnh nào. Bắt đầu giao dịch để xem phân tích AI.',
      'journal_playing_voice': 'Đang phát phân tích giọng nói...',
      'journal_export_csv': 'Xuất CSV',
      'journal_filter': 'Lọc',
      'journal_heatmap_title': 'BẢN ĐỔ NHIỆT LỜI/LỔ',
      'journal_no_trades_cell': 'Không có lệnh',
      'journal_heatmap_loss': 'Lỗ',
      'journal_heatmap_profit': 'Lãi',
      'journal_trade_log': 'NHẬT KÝ LỆNH TỔNG',
      'journal_lots': 'Lot',
      // News Feed Screen
      'news_page_title': 'Thông Tin Thị Trường',
      'news_page_desc':
          'Tin tức và tâm lý thị trường từ các nguồn đang khả dụng.',
      'news_sentiment_title': 'CHỈ SỐ TÂM LÝ TOÀN CẦU',
      'news_bullish': 'TÂM LÝ THị TRƯỜNG: TĂNG',
      'news_bearish': 'TÂM LÝ THị TRƯỜNG: GIẢM',
      'news_neutral_bullish': 'TÂM LÝ THị TRƯỜNG: TRUNG TÍNH-TĂNG',
      'news_neutral_bearish': 'TÂM LÝ THị TRƯỜNG: TRUNG TÍNH-GIẢM',
      'news_fear': 'SỢ HÃI',
      'news_neutral': 'TRUNG TÍNH',
      'news_greed': 'THAM LAM',
      'news_no_articles': 'Không có bài báo nào',
      'news_ai_placeholder': 'Hỏi về tâm lý thị trường...',
      'news_ai_title': 'PHÂN TÍCH THỊ TRƯỜNG AI',
      'news_ai_clear_tooltip': 'Xóa lịch sử chat',
      'news_ai_clear_title': 'Xóa lịch sử?',
      'news_ai_clear_content': 'Tất cả lịch sử chat sẽ bị xóa vĩnh viễn.',
      'news_ai_cancel': 'Hủy',
      'news_ai_delete': 'Xóa',
      'news_ai_empty_hint': 'Hỏi AI về tin tức\nvà phân tích thị trường',
      'news_ai_welcome':
          'Hỏi về tâm lý thị trường, tác động tin tức hoặc phân tích giao dịch. Câu trả lời chỉ khả dụng khi dịch vụ AI đã được cấu hình.',
      // ─── Profile Screen ───
      'profile_title': 'Bảo Mật & Hồ Sơ',
      'profile_subtitle':
          'Quản lý danh tính, tài khoản sàn và hạn mức API của bạn.',
      'profile_system_online': '● HỆ THỐNG PROTRADING AI TRỰC TUYẾN',
      'profile_connecting': '○ ĐANG KẾT NỐI...',
      // Profile Info
      'profile_edit_username': 'Chỉnh Sửa Tên',
      'profile_new_username': 'Tên mới',
      'profile_username_updated': 'Đã cập nhật tên!',
      'profile_username_update_failed': 'Không thể cập nhật tên.',
      'profile_save': 'LƯU',
      // Change Password
      'profile_change_key': 'Đổi Mật Khẩu Truy Cập',
      'profile_current_password': 'Mật Khẩu Hiện Tại',
      'profile_new_password': 'Mật Khẩu Mới',
      'profile_confirm_password': 'Xác Nhận Mật Khẩu Mới',
      'profile_password_mismatch': 'Mật khẩu không khớp!',
      'profile_password_short': 'Mật khẩu phải có ít nhất 6 ký tự!',
      'profile_password_change_failed':
          'Không thể đổi mật khẩu. Hãy kiểm tra mật khẩu hiện tại và thử lại.',
      'profile_password_changed': 'Đổi mật khẩu thành công!',
      'profile_change_btn': 'ĐỔI',
      // Broker Accounts
      'profile_broker_accounts': 'TÀI KHOẢN SÀN',
      'profile_link_new': 'LIÊN KẾT MỚI',
      'profile_no_accounts': 'Chưa có tài khoản nào được liên kết.',
      'profile_link_broker_title': 'Liên Kết Tài Khoản Sàn',
      'profile_platform': 'Nền Tảng',
      'profile_broker_server': 'Server Sàn (VD: Exness-Real10)',
      'profile_login_id': 'ID Đăng Nhập',
      'profile_trading_password': 'Mật Khẩu Giao Dịch',
      'profile_security_notice':
          'App chỉ yêu cầu Mật khẩu chỉ đọc để đồng bộ. Tuyệt đối an toàn, hệ thống KHÔNG THỂ vào lệnh hoặc rút tiền ra bạn.',
      'profile_link_account': 'LIÊN KẾT',
      'profile_link_sent':
          'Đã gửi yêu cầu liên kết. Kiểm tra trạng thái sau ít phút.',
      'profile_link_failed': 'Không thể liên kết tài khoản sàn.',
      // Quota
      'profile_api_requests': 'YÊU CẦU API',
      'profile_backtest_sessions': 'PHIÊN BACKTEST',
      'profile_neural_storage': 'LƯU TRỮ AI',
      // Security
      'profile_security_settings': 'CÀI ĐẶT BẢO MẬT',
      'profile_2fa_title': 'Xác Thực 2 Lớp (2FA)',
      'profile_2fa_subtitle': 'Bảo vệ tài khoản bằng xác thực 2 bước.',
      'profile_2fa_unavailable':
          'Chưa thể thiết lập 2FA khi Firebase MFA chưa được cấu hình.',
      'profile_2fa_enabled': 'Đã bật 2FA',
      'profile_2fa_disabled': 'Đã tắt 2FA',
      // Preferences
      'profile_preferences': 'TÙY CHỈNH',
      'profile_push_notifications': 'Thông Báo Đẩy',
      'profile_push_notifications_subtitle':
          'Nhận tín hiệu giao dịch và cảnh báo',
      'profile_language': 'Ngôn Ngữ',
      'profile_language_vi': 'Tiếng Việt',
      'profile_language_en': 'English',
      'profile_data_sharing': 'Chia Sẻ Dữ Liệu Gỡ Lỗi',
      'profile_data_sharing_subtitle':
          'Cho phép chia sẻ dữ liệu gỡ lỗi hệ thống (Mặc định: TẮT)',
      // Stats
      'profile_trades': 'LỆNH',
      'profile_win_rate': 'TỶ LỆ THẮNG',
      'profile_rank': 'HẠNG',
      // Day 5
      'profile_link_on_web_only':
          'Liên kết MT4/MT5 chỉ trên Web (Profile → Link Broker). Mobile dùng API Relay — không nhập mật khẩu sàn trên thiết bị.',
      'sync_gate_title': 'KẾT NỐI SÀN GIAO DỊCH',
      'sync_gate_body':
          'Liên kết MT4/MT5 trên Web để mở khóa relay live, Journal rõ ràng và đồng bộ rủi ro. Hoặc tiếp tục chế độ thủ công với Input Constraint.',
      'sync_gate_connect': 'KẾT NỐI NGAY',
      'sync_gate_skip': 'BỎ QUA & NHẬP THỦ CÔNG',
      'journal_locked_title': 'JOURNAL ĐÃ KHÓA',
      'journal_locked_body':
          'Liên kết sàn trên Web (Profile → Link Broker) để mở khóa phân tích Journal đầy đủ.',
      'ai_fallback_label': 'CHẾ ĐỘ DỰ PHÒNG',
    },
  };

  static String get(String langCode, String key) {
    return _localizedValues[langCode]?[key] ?? key;
  }
}

extension LocalizationExtension on BuildContext {
  String tr(String key) {
    final langCode = watch<LocaleCubit>().state;
    return AppLocalizations.get(langCode, key);
  }
}
